name: Build and deploy Node.js app to Azure Web App - nextjs-demo-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Build Next.js app
        run: |
          npm run build

      - name: Zip production artifacts for deployment
        run: |
          mkdir deploy
          cp -r .next/standalone deploy/ # Copy the standalone build
          cp -r public deploy/          # Copy the public folder
          cp package.json deploy/       # Include package.json
          cp package-lock.json deploy/  # Include package-lock.json
          cd deploy && zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nextjs-demo-app'                # Your Azure Web App name
          slot-name: 'Production'                    # The slot you're deploying to
          package: .                                  # Path to your app's root directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_59C3096855CB4B5AAD6962F91042528F }}
