name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APPLICATION_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_59C3096855CB4B5AAD6962F91042528F }}
  WEBAPP_NAME: "nextjs-demo-app"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: |
          npm install

      - name: Build Next.js app
        run: |
          npm run build
          npm run export # Ensure a static build

      - name: Prepare deployment folder
        run: |
          mkdir -p ./build/standalone
          cp -r .next/standalone ./build/standalone # Copy the standalone folder
          cp -r public ./build/standalone           # Copy the public folder
          cp package.json ./build/standalone        # Include package.json
          cp package-lock.json ./build/standalone   # Include package-lock.json
          cp -r node_modules ./build/standalone     # Include node_modules

      - name: Zip production artifacts
        run: |
          cd ./build && zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./deploy

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ env.APPLICATION_PUBLISH_PROFILE }}
          package: ./deploy
