deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Unzip artifact for deployment
      run: unzip release.zip -d deploy

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'nextjs-demo-app'                # Your Azure Web App name
        slot-name: 'Production'                    # The slot you're deploying to
        package: ./deploy                          # Path to the deployed directory
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_59C3096855CB4B5AAD6962F91042528F }}
